package com.aotain.zongfen.dto.monitor;

import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zf_v2_monitor_onlineuser_detail
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Setter
@Getter
@NoArgsConstructor
public class MonitorOnlineuserDetailDTO implements Serializable {

    /**
     * 时间跨度
     */
    private String startTime;

    private String endTime;

    private String statTime;

    /**
     * Database Column Remarks:
     *   服务器IP

     * @mbg.generated
     */
    private String serverIp;

    /**
     * Database Column Remarks:
     *   统计粒度,0=5分钟，1=小时， 2=天
     *

     * @mbg.generated
     */
    private Byte statType;

    /**
     * Database Column Remarks:
     *   在线用户数

     * @mbg.generated
     */
    private Integer onlineusernum;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_monitor_onlineuser_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;


}