package com.aotain.zongfen.mapper.zfpush;


import com.aotain.common.config.annotation.MyBatisDao;
import com.aotain.zongfen.model.zfpush.ZfV2PushMessage;

import java.util.List;

@MyBatisDao
public interface ZfV2PushMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_push_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long pushid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_push_message
     *
     * @mbg.generated
     */
    int insert(ZfV2PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_push_message
     *
     * @mbg.generated
     */
    ZfV2PushMessage selectByPrimaryKey(Long pushid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_push_message
     *
     * @mbg.generated
     */
    List<ZfV2PushMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_push_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZfV2PushMessage record);
}