package com.aotain.zongfen.mapper.general;

import com.aotain.common.config.annotation.MyBatisDao;
import com.aotain.zongfen.model.general.ZfV2GenIpImporttask;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface ZfV2GenIpImporttaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_gen_ip_importtask
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_gen_ip_importtask
     *
     * @mbg.generated
     */
    int insert(ZfV2GenIpImporttask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_gen_ip_importtask
     *
     * @mbg.generated
     */
    ZfV2GenIpImporttask selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_gen_ip_importtask
     *
     * @mbg.generated
     */
    ZfV2GenIpImporttask selectOne();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zf_v2_gen_ip_importtask
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZfV2GenIpImporttask record);

    List<ZfV2GenIpImporttask> selectAll();

    ZfV2GenIpImporttask selectByUserId(@Param("userid") Integer userId);
}