package com.aotain.zongfen.model.general;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zf_v2_gen_ip_importtask
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Setter
@Getter
public class ZfV2GenIpImporttask {
    /**
     * Database Column Remarks:
     *   任务ID
     *
     * @mbg.generated
     */
    private Integer taskId;

    /**
     * Database Column Remarks:
     *   导入文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_gen_ip_importtask.filename
     *
     * @mbg.generated
     */
    private String filename;

    /**
     * Database Column Remarks:
     *   导入类型，0=全量，1=增量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_gen_ip_importtask.import_type
     *
     * @mbg.generated
     */
    private String importType;

    /**
     * Database Column Remarks:
     *   状态, 0=正在导入，1=导入成功，2=导入异常
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_gen_ip_importtask.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   结果文件名，导入异常有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_gen_ip_importtask.result_file
     *
     * @mbg.generated
     */
    private String resultFile;

    /**
     * Database Column Remarks:
     *   操作用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_gen_ip_importtask.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_gen_ip_importtask.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_gen_ip_importtask.finish_time
     *
     * @mbg.generated
     */
    private Date finishTime;

    private String serverIp;

    @Override
    public String toString() {
        return "ZfV2GenIpImporttask{" +
                "taskId=" + taskId +
                ", filename='" + filename + '\'' +
                ", importType='" + importType + '\'' +
                ", status=" + status +
                ", resultFile='" + resultFile + '\'' +
                ", userid=" + userid +
                ", createTime=" + createTime +
                ", finishTime=" + finishTime +
                ", serverIp='" + serverIp + '\'' +
                '}';
    }
}