package com.aotain.zongfen.model.zfpush;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zf_v2_push_message
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ZfV2PushMessage {
    /**
     * Database Column Remarks:
     *   推送ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.pushid
     *
     * @mbg.generated
     */
    private Long pushid;

    /**
     * Database Column Remarks:
     *   推送类型，1-邮件、2-短信、3-微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.push_type
     *
     * @mbg.generated
     */
    private Integer pushType;

    /**
     * Database Column Remarks:
     *   主题类型，1=系统，2=拨测
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.subject_type
     *
     * @mbg.generated
     */
    private Integer subjectType;

    /**
     * Database Column Remarks:
     *   邮件主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.mail_subject
     *
     * @mbg.generated
     */
    private String mailSubject;

    /**
     * Database Column Remarks:
     *   推送状态，0-未推送、1-推送中、2-推送成功、3-推送失败'
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.push_status
     *
     * @mbg.generated
     */
    private Integer pushStatus;

    /**
     * Database Column Remarks:
     *   重发次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.repush_times
     *
     * @mbg.generated
     */
    private Integer repushTimes;

    /**
     * Database Column Remarks:
     *   调用服务器
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.server_ip
     *
     * @mbg.generated
     */
    private String serverIp;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   告警消息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.alarm_message
     *
     * @mbg.generated
     */
    private byte[] alarmMessage;

    /**
     * Database Column Remarks:
     *   推送内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zf_v2_push_message.push_content
     *
     * @mbg.generated
     */
    private byte[] pushContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.pushid
     *
     * @return the value of zf_v2_push_message.pushid
     *
     * @mbg.generated
     */
    public Long getPushid() {
        return pushid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.pushid
     *
     * @param pushid the value for zf_v2_push_message.pushid
     *
     * @mbg.generated
     */
    public void setPushid(Long pushid) {
        this.pushid = pushid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.push_type
     *
     * @return the value of zf_v2_push_message.push_type
     *
     * @mbg.generated
     */
    public Integer getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.push_type
     *
     * @param pushType the value for zf_v2_push_message.push_type
     *
     * @mbg.generated
     */
    public void setPushType(Integer pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.subject_type
     *
     * @return the value of zf_v2_push_message.subject_type
     *
     * @mbg.generated
     */
    public Integer getSubjectType() {
        return subjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.subject_type
     *
     * @param subjectType the value for zf_v2_push_message.subject_type
     *
     * @mbg.generated
     */
    public void setSubjectType(Integer subjectType) {
        this.subjectType = subjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.mail_subject
     *
     * @return the value of zf_v2_push_message.mail_subject
     *
     * @mbg.generated
     */
    public String getMailSubject() {
        return mailSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.mail_subject
     *
     * @param mailSubject the value for zf_v2_push_message.mail_subject
     *
     * @mbg.generated
     */
    public void setMailSubject(String mailSubject) {
        this.mailSubject = mailSubject == null ? null : mailSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.push_status
     *
     * @return the value of zf_v2_push_message.push_status
     *
     * @mbg.generated
     */
    public Integer getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.push_status
     *
     * @param pushStatus the value for zf_v2_push_message.push_status
     *
     * @mbg.generated
     */
    public void setPushStatus(Integer pushStatus) {
        this.pushStatus = pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.repush_times
     *
     * @return the value of zf_v2_push_message.repush_times
     *
     * @mbg.generated
     */
    public Integer getRepushTimes() {
        return repushTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.repush_times
     *
     * @param repushTimes the value for zf_v2_push_message.repush_times
     *
     * @mbg.generated
     */
    public void setRepushTimes(Integer repushTimes) {
        this.repushTimes = repushTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.server_ip
     *
     * @return the value of zf_v2_push_message.server_ip
     *
     * @mbg.generated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.server_ip
     *
     * @param serverIp the value for zf_v2_push_message.server_ip
     *
     * @mbg.generated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.create_time
     *
     * @return the value of zf_v2_push_message.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.create_time
     *
     * @param createTime the value for zf_v2_push_message.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.update_time
     *
     * @return the value of zf_v2_push_message.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.update_time
     *
     * @param updateTime the value for zf_v2_push_message.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.alarm_message
     *
     * @return the value of zf_v2_push_message.alarm_message
     *
     * @mbg.generated
     */
    public byte[] getAlarmMessage() {
        return alarmMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.alarm_message
     *
     * @param alarmMessage the value for zf_v2_push_message.alarm_message
     *
     * @mbg.generated
     */
    public void setAlarmMessage(byte[] alarmMessage) {
        this.alarmMessage = alarmMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zf_v2_push_message.push_content
     *
     * @return the value of zf_v2_push_message.push_content
     *
     * @mbg.generated
     */
    public byte[] getPushContent() {
        return pushContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zf_v2_push_message.push_content
     *
     * @param pushContent the value for zf_v2_push_message.push_content
     *
     * @mbg.generated
     */
    public void setPushContent(byte[] pushContent) {
        this.pushContent = pushContent;
    }
}